/**
 * Create new order
 */
export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'

/**
 * Get order details
 */
export const GET_ORDER_DETAILS_REQUEST = 'GET_ORDER_DETAILS_REQUEST'
export const GET_ORDER_DETAILS_SUCCESS = 'GET_ORDER_DETAILS_SUCCESS'
export const GET_ORDER_DETAILS_FAIL = 'GET_ORDER_DETAILS_FAIL'
/**
 * Update order To Paid
 */
export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'
/**
 * Update order To Delivred
 */
export const ORDER_DELIVRED_REQUEST = 'ORDER_DELIVRED_REQUEST'
export const ORDER_DELIVRED_SUCCESS = 'ORDER_DELIVRED_SUCCESS'
export const ORDER_DELIVRED_FAIL = 'ORDER_DELIVRED_FAIL'
export const ORDER_DELIVRED_RESET = 'ORDER_DELIVRED_RESET'
/**
 * Get config paypal client id
 */
export const GET_CONFIG_REQUEST = 'GET_CONFIG_REQUEST'
export const GET_CONFIG_SUCCESS = 'GET_CONFIG_SUCCESS'
export const GET_CONFIG_FAIL = 'GET_CONFIG_FAIL'
/**
 * Get myOrders
 */
export const GET_MY_ORDERS_REQUEST = 'GET_MY_ORDERS_REQUEST'
export const GET_MY_ORDERS_SUCCESS = 'GET_MY_ORDERS_SUCCESS'
export const GET_MY_ORDERS_FAIL = 'GET_MY_ORDERS_FAIL'

/**
 * Get All orders
 */
export const GET_ALL_ORDERS_REQUEST = 'GET_ALL_ORDERS_REQUEST'
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS'
export const GET_ALL_ORDERS_FAIL = 'GET_ALL_ORDERS_FAIL'


/**
 * Reset Order
 */
export const RESET_ORDER = 'RESET_ORDER'
