/**
 * Add to cart item
 */
export const CART_ADD_ITEM_REQUEST = 'CART_ADD_ITEM_REQUEST'
export const CART_ADD_ITEM_SUCCESS = 'CART_ADD_ITEM_SUCCESS'
export const CART_ADD_ITEM_FAIL = 'CART_ADD_ITEM_FAIL'

/**
 * Remove from cart item
 */
export const CART_REMOVE_ITEM_REQUEST = 'CART_REMOVE_ITEM_REQUEST'
export const CART_REMOVE_ITEM_SUCCESS = 'CART_REMOVE_ITEM_SUCCESS'
export const CART_REMOVE_ITEM_FAIL = 'CART_REMOVE_ITEM_FAIL'
/**
 * save shipping adress
 */
export const CART_SAVE_ADDRESS_REQUEST = 'CART_SAVE_ADDRESS_REQUEST'
export const CART_SAVE_ADDRESS_SUCCESS = 'CART_SAVE_ADDRESS_SUCCESS'
export const CART_SAVE_ADDRESS_FAIL = 'CART_SAVE_ADDRESS_FAIL'
/**
 * save payment method
 */
export const CART_SAVE_PAYMENT_METHOD_REQUEST = 'CART_SAVE_PAYMENT_METHOD_REQUEST'
export const CART_SAVE_PAYMENT_METHOD_SUCCESS = 'CART_SAVE_PAYMENT_METHOD_SUCCESS'
export const CART_SAVE_PAYMENT_METHOD_FAIL = 'CART_SAVE_PAYMENT_METHOD_FAIL'
