/**
 * login
 */
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
/**
 * login with facebook or google
 */
export const USER_LOGIN_FG_REQUEST = 'USER_LOGIN_FG_REQUEST'
export const USER_LOGIN_FG_SUCCESS = 'USER_LOGIN_FG_SUCCESS'
export const USER_LOGIN_FG_FAIL = 'USER_LOGIN_FG_FAIL'
/**
 * Register
 */
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

/**
 * logout
 */
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST'
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL'