/**
 * get user details
 */
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'


/**
 * update profile
 */
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'

/**
 * Reset update
 */
export const USER_RESET_REQUEST = 'USER_RESET_REQUEST'
export const USER_RESET_SUCCESS = 'USER_RESET_SUCCESS'
export const USER_RESET_FAIL = 'USER_RESET_FAIL'

/**
 * Get user List
 */
export const GET_USERS_LIST_REQUEST = 'GET_USERS_LIST_REQUEST'
export const GET_USERS_LIST_SUCCESS = 'GET_USERS_LIST_SUCCESS'
export const GET_USERS_LIST_FAIL = 'GET_USERS_LIST_FAIL'
/**
 * Delete user
 */
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'
/**
 * update user by admin
 */
export const ADMIN_USER_UPDATE_REQUEST = 'ADMIN_USER_UPDATE_REQUEST'
export const ADMIN_USER_UPDATE_SUCCESS = 'ADMIN_USER_UPDATE_SUCCESS'
export const ADMIN_USER_UPDATE_FAIL = 'ADMIN_USER_UPDATE_FAIL'
/**
 * get user details by admin
 */
export const ADMIN_GET_USER_DETAILS_REQUEST = 'ADMIN_GET_USER_DETAILS_REQUEST'
export const ADMIN_GET_USER_DETAILS_SUCCESS = 'ADMIN_GET_USER_DETAILS_SUCCESS'
export const ADMIN_GET_USER_DETAILS_FAIL = 'ADMIN_GET_USER_DETAILS_FAIL'
export const ADMIN_RESET_UPDATE_USER = 'ADMIN_RESET_UPDATE_USER'
