/**
 * get user details
 */
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'


/**
 * update profile
 */
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'

/**
 * Reset update
 */
export const USER_RESET_REQUEST = 'USER_RESET_REQUEST'
export const USER_RESET_SUCCESS = 'USER_RESET_SUCCESS'
export const USER_RESET_FAIL = 'USER_RESET_FAIL'